import re
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime

from app.core.enums import DetectorType, ScriptKind
from app.remediation.scripts.templates import (
    BULK_FUNCTIONS,
    BULK_MAIN_CLOSE,
    BULK_MAIN_OPEN,
    COMMON_FUNCTIONS,
    EBS_DELETE_BODY,
    EBS_INVESTIGATION_BODY,
    EC2_INVESTIGATION_BODY,
    EIP_INVESTIGATION_BODY,
    EIP_RELEASE_BODY,
    INVESTIGATION_PREAMBLE,
    SHEBANG,
    SNAPSHOT_INVESTIGATION_BODY,
    STRICT_MODE,
)
from app.remediation.validators import (
    IdentifierKind,
    ValidatedIdentifier,
    validate_account_id,
    validate_allocation_id,
    validate_instance_id,
    validate_region,
    validate_scan_id,
    validate_snapshot_id,
    validate_tag_key,
    validate_tag_value,
    validate_volume_id,
)

_READONLY = re.compile(r'^readonly [A-Z_]+="[A-Za-z0-9_.:/+@-]*"$')
_EXPECTED_KINDS = {
    DetectorType.UNATTACHED_EBS_VOLUME: IdentifierKind.VOLUME_ID,
    DetectorType.UNASSOCIATED_ELASTIC_IP: IdentifierKind.ALLOCATION_ID,
    DetectorType.STOPPED_EC2_INSTANCE: IdentifierKind.INSTANCE_ID,
    DetectorType.SNAPSHOT_MISSING_SOURCE_VOLUME: IdentifierKind.SNAPSHOT_ID,
}
_RESOURCE_VARIABLES = {
    DetectorType.UNATTACHED_EBS_VOLUME: "VOLUME_ID",
    DetectorType.UNASSOCIATED_ELASTIC_IP: "ALLOCATION_ID",
    DetectorType.STOPPED_EC2_INSTANCE: "INSTANCE_ID",
    DetectorType.SNAPSHOT_MISSING_SOURCE_VOLUME: "SNAPSHOT_ID",
}
_INVESTIGATION_BODIES = {
    DetectorType.UNATTACHED_EBS_VOLUME: EBS_INVESTIGATION_BODY,
    DetectorType.UNASSOCIATED_ELASTIC_IP: EIP_INVESTIGATION_BODY,
    DetectorType.STOPPED_EC2_INSTANCE: EC2_INVESTIGATION_BODY,
    DetectorType.SNAPSHOT_MISSING_SOURCE_VOLUME: SNAPSHOT_INVESTIGATION_BODY,
}
_INVESTIGATION_ACTIONS = {
    DetectorType.UNATTACHED_EBS_VOLUME: "investigate-volume",
    DetectorType.UNASSOCIATED_ELASTIC_IP: "investigate-address",
    DetectorType.STOPPED_EC2_INSTANCE: "investigate-instance",
    DetectorType.SNAPSHOT_MISSING_SOURCE_VOLUME: "investigate-snapshot",
}


@dataclass(frozen=True)
class ScriptTarget:
    region: ValidatedIdentifier
    resource_id: ValidatedIdentifier


@dataclass(frozen=True)
class GeneratedScript:
    kind: ScriptKind
    filename: str
    content: str
    checks: list[str]
    warnings: list[str]


def _require_kind(identifier: ValidatedIdentifier, kind: IdentifierKind) -> None:
    if identifier.kind != kind:
        raise ValueError(f"expected {kind.value}, got {identifier.kind.value}")


def _timestamp(generated_at: datetime) -> str:
    if generated_at.tzinfo is None or generated_at.utcoffset() is None:
        raise ValueError("generated_at must be timezone-aware")
    return generated_at.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _scan_value(scan_id: ValidatedIdentifier | None) -> str:
    return scan_id.value if scan_id else "none"


def _header(
    *,
    title: str,
    kind: ScriptKind,
    detector: str,
    generated_at: datetime,
    scan_id: ValidatedIdentifier | None,
    account_id: ValidatedIdentifier,
    region: str,
    resource: str | None = None,
    targets: Sequence[tuple[DetectorType, ScriptTarget]] = (),
) -> str:
    lines = [
        f"# Generated by CloudZombie - {title}",
        f"# Kind:             {kind.value}",
        f"# Detector:         {detector}",
        f"# Generated at:     {_timestamp(generated_at)}",
        f"# Scan ID:          {_scan_value(scan_id)}",
        f"# Expected account: {account_id.value}",
        f"# Region:           {region}",
    ]
    if resource is not None:
        lines.append(f"# Resource:         {resource}")
    else:
        lines.append("# Resources:")
        lines.extend(
            f"#   {target.region.value}  {target.resource_id.value}" for _, target in targets
        )
    lines.extend(
        [
            "#",
            "# CloudZombie never executes this script. It analyses AWS through read-only API calls",
            "# only and generates this file for a human to review and run separately. Every "
            "AWS CLI",
            "# call below names the region explicitly, re-validates the live resource state, and",
            "# aborts on any unexpected condition.",
            "",
        ]
    )
    return "\n".join(lines)


def _validate_common(
    account_id: ValidatedIdentifier,
    scan_id: ValidatedIdentifier | None,
    ignore_tag_key: ValidatedIdentifier,
    ignore_tag_value: ValidatedIdentifier,
) -> None:
    _require_kind(account_id, IdentifierKind.ACCOUNT_ID)
    validate_account_id(account_id.value)
    if scan_id is not None:
        _require_kind(scan_id, IdentifierKind.SCAN_ID)
        validate_scan_id(scan_id.value)
    _require_kind(ignore_tag_key, IdentifierKind.TAG_KEY)
    _require_kind(ignore_tag_value, IdentifierKind.TAG_VALUE)
    validate_tag_key(ignore_tag_key.value)
    validate_tag_value(ignore_tag_value.value)


def _validate_target(detector_type: DetectorType, target: ScriptTarget) -> None:
    _require_kind(target.region, IdentifierKind.REGION)
    validate_region(target.region.value)
    expected = _EXPECTED_KINDS[detector_type]
    _require_kind(target.resource_id, expected)
    {
        IdentifierKind.VOLUME_ID: validate_volume_id,
        IdentifierKind.ALLOCATION_ID: validate_allocation_id,
        IdentifierKind.INSTANCE_ID: validate_instance_id,
        IdentifierKind.SNAPSHOT_ID: validate_snapshot_id,
    }[expected](target.resource_id.value)


def _assert_safe(content: str) -> None:
    for line in content.splitlines():
        if line.startswith("readonly ") and _READONLY.fullmatch(line) is None:
            raise AssertionError(f"unsafe readonly assignment: {line!r}")
    if any(character != "\n" and not 32 <= ord(character) <= 126 for character in content):
        raise AssertionError("generated script contains non-ASCII or non-printable characters")


def _readonly(name: str, value: str) -> str:
    return f'readonly {name}="{value}"\n'


def generate_script(
    *,
    kind: ScriptKind,
    detector_type: DetectorType,
    account_id: ValidatedIdentifier,
    target: ScriptTarget,
    scan_id: ValidatedIdentifier | None,
    generated_at: datetime,
    ignore_tag_key: ValidatedIdentifier,
    ignore_tag_value: ValidatedIdentifier,
) -> GeneratedScript:
    _validate_common(account_id, scan_id, ignore_tag_key, ignore_tag_value)
    _validate_target(detector_type, target)
    if kind == ScriptKind.GUARDED_REMEDIATION and detector_type not in {
        DetectorType.UNATTACHED_EBS_VOLUME,
        DetectorType.UNASSOCIATED_ELASTIC_IP,
    }:
        raise ValueError("this detector has no guarded remediation body")

    investigation = kind == ScriptKind.INVESTIGATION
    title = "read-only investigation script" if investigation else "guarded remediation script"
    header = _header(
        title=title,
        kind=kind,
        detector=detector_type.value,
        generated_at=generated_at,
        scan_id=scan_id,
        account_id=account_id,
        region=target.region.value,
        resource=target.resource_id.value,
    )
    assignments = _readonly("EXPECTED_ACCOUNT_ID", account_id.value)
    assignments += _readonly("REGION", target.region.value)
    assignments += _readonly(_RESOURCE_VARIABLES[detector_type], target.resource_id.value)
    if not investigation:
        assignments += _readonly("IGNORE_TAG_KEY", ignore_tag_key.value)
        assignments += _readonly("IGNORE_TAG_VALUE", ignore_tag_value.value)
        assignments += _readonly("CLOUDFORMATION_TAG_KEY", "aws:cloudformation:stack-name")
    if investigation:
        body = INVESTIGATION_PREAMBLE + _INVESTIGATION_BODIES[detector_type]
        action = _INVESTIGATION_ACTIONS[detector_type]
        checks = ["read-only describe commands only"]
        if detector_type == DetectorType.SNAPSHOT_MISSING_SOURCE_VOLUME:
            checks.append("deletion command present only as a comment")
    elif detector_type == DetectorType.UNATTACHED_EBS_VOLUME:
        body = EBS_DELETE_BODY
        action = "delete-volume"
        checks = [
            f"account verification for {account_id.value}",
            f"explicit region {target.region.value}",
            "live state re-fetch: volume available with 0 attachments",
            "ignore-tag abort",
            "CloudFormation-tag abort",
            f"exact confirmation phrase DELETE {target.resource_id.value}",
        ]
    else:
        body = EIP_RELEASE_BODY
        action = "release-address"
        checks = [
            f"account verification for {account_id.value}",
            f"explicit region {target.region.value}",
            "live state re-fetch: address remains unassociated",
            "ignore-tag abort",
            "CloudFormation-tag abort",
            f"exact confirmation phrase RELEASE {target.resource_id.value}",
        ]
    warnings = ["CloudZombie cannot prove ownership."]
    if detector_type == DetectorType.UNATTACHED_EBS_VOLUME:
        warnings.insert(0, "An optional pre-deletion snapshot incurs storage charges.")
    elif detector_type == DetectorType.UNASSOCIATED_ELASTIC_IP:
        warnings.insert(0, "Releasing an Elastic IP may be irrecoverable.")
    content = SHEBANG + header + STRICT_MODE + assignments + "\n" + COMMON_FUNCTIONS + body
    _validate_common(account_id, scan_id, ignore_tag_key, ignore_tag_value)
    _validate_target(detector_type, target)
    _assert_safe(content)
    filename = f"cloudzombie-{action}-{target.resource_id.value}-{target.region.value}.sh"
    return GeneratedScript(kind, filename, content, checks, warnings)


def generate_bulk_script(
    *,
    account_id: ValidatedIdentifier,
    targets: Sequence[tuple[DetectorType, ScriptTarget]],
    scan_id: ValidatedIdentifier | None,
    generated_at: datetime,
    ignore_tag_key: ValidatedIdentifier,
    ignore_tag_value: ValidatedIdentifier,
) -> GeneratedScript:
    if not targets:
        raise ValueError("bulk script requires at least one target")
    _validate_common(account_id, scan_id, ignore_tag_key, ignore_tag_value)
    for detector_type, target in targets:
        if detector_type not in {
            DetectorType.UNATTACHED_EBS_VOLUME,
            DetectorType.UNASSOCIATED_ELASTIC_IP,
        }:
            raise ValueError("bulk scripts support only EBS volumes and Elastic IPs")
        _validate_target(detector_type, target)
    first_region = targets[0][1].region.value
    header = _header(
        title="guarded bulk remediation script",
        kind=ScriptKind.GUARDED_REMEDIATION,
        detector="multiple",
        generated_at=generated_at,
        scan_id=scan_id,
        account_id=account_id,
        region="multiple; see resources",
        targets=targets,
    )
    assignments = _readonly("EXPECTED_ACCOUNT_ID", account_id.value)
    assignments += _readonly("REGION", first_region)
    assignments += (
        "# REGION is used only for the STS identity check; each resource names its own region.\n"
    )
    assignments += _readonly("IGNORE_TAG_KEY", ignore_tag_key.value)
    assignments += _readonly("IGNORE_TAG_VALUE", ignore_tag_value.value)
    assignments += _readonly("CLOUDFORMATION_TAG_KEY", "aws:cloudformation:stack-name")
    calls = "".join(
        (
            f'  process_volume "{target.region.value}" "{target.resource_id.value}"\n'
            if detector_type == DetectorType.UNATTACHED_EBS_VOLUME
            else f'  process_address "{target.region.value}" "{target.resource_id.value}"\n'
        )
        for detector_type, target in targets
    )
    content = (
        SHEBANG
        + header
        + STRICT_MODE
        + assignments
        + "\n"
        + COMMON_FUNCTIONS
        + BULK_FUNCTIONS
        + BULK_MAIN_OPEN
        + calls
        + BULK_MAIN_CLOSE
    )
    _validate_common(account_id, scan_id, ignore_tag_key, ignore_tag_value)
    for detector_type, target in targets:
        _validate_target(detector_type, target)
    _assert_safe(content)
    timestamp = _timestamp(generated_at).replace("-", "").replace(":", "")
    filename = f"cloudzombie-bulk-remediation-{timestamp}.sh"
    return GeneratedScript(
        ScriptKind.GUARDED_REMEDIATION,
        filename,
        content,
        [
            f"account verification for {account_id.value}",
            "explicit region per resource",
            "live state re-fetch per resource",
            "ignore-tag abort",
            "CloudFormation-tag abort",
            "exact confirmation phrase per resource",
        ],
        [
            "Releasing an Elastic IP may be irrecoverable.",
            "An optional snapshot is not offered in bulk mode.",
            "CloudZombie cannot prove ownership.",
        ],
    )
