#!/usr/bin/env bash
# Generated by CloudZombie - guarded bulk remediation script
# Kind:             guarded_remediation
# Detector:         multiple
# Generated at:     2026-09-20T10:00:00Z
# Scan ID:          11111111-1111-4111-8111-111111111111
# Expected account: 123456789012
# Region:           multiple; see resources
# Resources:
#   eu-central-1  vol-0a1b2c3d4e5f60001
#   us-east-1  vol-0a1b2c3d4e5f60002
#   us-east-1  eipalloc-0a1b2c3d4e5f60001
#
# CloudZombie never executes this script. It analyses AWS through read-only API calls
# only and generates this file for a human to review and run separately. Every AWS CLI
# call below names the region explicitly, re-validates the live resource state, and
# aborts on any unexpected condition.
set -euo pipefail
readonly EXPECTED_ACCOUNT_ID="123456789012"
readonly REGION="eu-central-1"
# REGION is used only for the STS identity check; each resource names its own region.
readonly IGNORE_TAG_KEY="cloudzombie:ignore"
readonly IGNORE_TAG_VALUE="true"
readonly CLOUDFORMATION_TAG_KEY="aws:cloudformation:stack-name"


abort() {
  echo
  echo "ABORTED"
  echo
  echo "$1"
  echo
  echo "No action performed."
  exit 1
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

require_aws_cli() {
  if ! command -v aws >/dev/null 2>&1; then
    abort "The AWS CLI (aws) is not installed or not on PATH."
  fi
}

verify_account() {
  local current_account
  if ! current_account="$(aws sts get-caller-identity --region "$REGION" --query Account --output text 2>/dev/null)"; then
    abort "Could not determine the current AWS account (aws sts get-caller-identity failed). Check your credentials."
  fi
  if [ "$current_account" != "$EXPECTED_ACCOUNT_ID" ]; then
    abort "Account mismatch.

Expected account: $EXPECTED_ACCOUNT_ID
Current account:  $current_account"
  fi
  echo "Account verified: $current_account"
}

SKIPPED=0
COMPLETED=0

skip() {
  echo
  echo "SKIPPED $1"
  echo "$2"
  echo "No action performed for $1."
  SKIPPED=$((SKIPPED + 1))
}

check_tags() {
  local describe_command="$1" id_flag="$2" region="$3" resource_id="$4" root="$5"
  local ignore_value stack_name
  ignore_value="$(aws ec2 "$describe_command" --region "$region" "$id_flag" "$resource_id" --query "${root}[0].Tags[?Key=='${IGNORE_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$ignore_value" != "None" ] && [ "$(to_lower "$ignore_value")" = "$(to_lower "$IGNORE_TAG_VALUE")" ]; then
    echo "Resource is now marked to be ignored ($IGNORE_TAG_KEY=$ignore_value)."
    return 1
  fi
  stack_name="$(aws ec2 "$describe_command" --region "$region" "$id_flag" "$resource_id" --query "${root}[0].Tags[?Key=='${CLOUDFORMATION_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$stack_name" != "None" ] && [ -n "$stack_name" ]; then
    echo "Resource now carries the $CLOUDFORMATION_TAG_KEY tag (stack: $stack_name)."
    return 1
  fi
  return 0
}

process_volume() {
  local region="$1" volume_id="$2" state attachment_count confirmation reason
  echo
  echo "=== EBS volume $volume_id ($region) ==="
  if ! state="$(aws ec2 describe-volumes --region "$region" --volume-ids "$volume_id" --query 'Volumes[0].State' --output text 2>/dev/null)"; then
    skip "$volume_id" "Volume not found in $region."
    return 0
  fi
  if [ "$state" != "available" ]; then
    skip "$volume_id" "Resource state changed since CloudZombie analysis (state: $state)."
    return 0
  fi
  attachment_count="$(aws ec2 describe-volumes --region "$region" --volume-ids "$volume_id" --query 'length(Volumes[0].Attachments)' --output text)"
  if [ "$attachment_count" != "0" ]; then
    skip "$volume_id" "Resource state changed since CloudZombie analysis ($attachment_count attachment(s))."
    return 0
  fi
  if ! reason="$(check_tags describe-volumes --volume-ids "$region" "$volume_id" Volumes)"; then
    skip "$volume_id" "$reason"
    return 0
  fi
  aws ec2 describe-volumes --region "$region" --volume-ids "$volume_id" --output table
  printf 'Type DELETE %s to delete this volume (anything else skips it): ' "$volume_id"
  read -r confirmation
  if [ "$confirmation" != "DELETE $volume_id" ]; then
    skip "$volume_id" "Confirmation did not match."
    return 0
  fi
  aws ec2 delete-volume --region "$region" --volume-id "$volume_id"
  echo "Deleted volume $volume_id in $region."
  COMPLETED=$((COMPLETED + 1))
}

process_address() {
  local region="$1" allocation_id="$2" association_id instance_id network_interface_id confirmation reason
  echo
  echo "=== Elastic IP $allocation_id ($region) ==="
  if ! association_id="$(aws ec2 describe-addresses --region "$region" --allocation-ids "$allocation_id" --query 'Addresses[0].AssociationId' --output text 2>/dev/null)"; then
    skip "$allocation_id" "Allocation not found in $region."
    return 0
  fi
  instance_id="$(aws ec2 describe-addresses --region "$region" --allocation-ids "$allocation_id" --query 'Addresses[0].InstanceId' --output text)"
  network_interface_id="$(aws ec2 describe-addresses --region "$region" --allocation-ids "$allocation_id" --query 'Addresses[0].NetworkInterfaceId' --output text)"
  if [ "$association_id" != "None" ] || [ "$instance_id" != "None" ] || [ "$network_interface_id" != "None" ]; then
    skip "$allocation_id" "Resource state changed since CloudZombie analysis (address is now associated)."
    return 0
  fi
  if ! reason="$(check_tags describe-addresses --allocation-ids "$region" "$allocation_id" Addresses)"; then
    skip "$allocation_id" "$reason"
    return 0
  fi
  aws ec2 describe-addresses --region "$region" --allocation-ids "$allocation_id" --output table
  echo "WARNING: a released Elastic IP may not be recoverable."
  printf 'Type RELEASE %s to release this address (anything else skips it): ' "$allocation_id"
  read -r confirmation
  if [ "$confirmation" != "RELEASE $allocation_id" ]; then
    skip "$allocation_id" "Confirmation did not match."
    return 0
  fi
  aws ec2 release-address --region "$region" --allocation-id "$allocation_id"
  echo "Released Elastic IP allocation $allocation_id in $region."
  COMPLETED=$((COMPLETED + 1))
}

bulk_summary() {
  echo
  echo "Completed: $COMPLETED   Skipped: $SKIPPED"
}

main() {
  require_aws_cli
  verify_account
  process_volume "eu-central-1" "vol-0a1b2c3d4e5f60001"
  process_volume "us-east-1" "vol-0a1b2c3d4e5f60002"
  process_address "us-east-1" "eipalloc-0a1b2c3d4e5f60001"
  bulk_summary
}

main "$@"
