#!/usr/bin/env bash
# Generated by CloudZombie - guarded remediation script
# Kind:             guarded_remediation
# Detector:         unattached_ebs_volume
# Generated at:     2026-09-20T10:00:00Z
# Scan ID:          11111111-1111-4111-8111-111111111111
# Expected account: 123456789012
# Region:           eu-central-1
# Resource:         vol-0a1b2c3d4e5f60001
#
# CloudZombie never executes this script. It analyses AWS through read-only API calls
# only and generates this file for a human to review and run separately. Every AWS CLI
# call below names the region explicitly, re-validates the live resource state, and
# aborts on any unexpected condition.
set -euo pipefail
readonly EXPECTED_ACCOUNT_ID="123456789012"
readonly REGION="eu-central-1"
readonly VOLUME_ID="vol-0a1b2c3d4e5f60001"
readonly IGNORE_TAG_KEY="cloudzombie:ignore"
readonly IGNORE_TAG_VALUE="true"
readonly CLOUDFORMATION_TAG_KEY="aws:cloudformation:stack-name"


abort() {
  echo
  echo "ABORTED"
  echo
  echo "$1"
  echo
  echo "No action performed."
  exit 1
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

require_aws_cli() {
  if ! command -v aws >/dev/null 2>&1; then
    abort "The AWS CLI (aws) is not installed or not on PATH."
  fi
}

verify_account() {
  local current_account
  if ! current_account="$(aws sts get-caller-identity --region "$REGION" --query Account --output text 2>/dev/null)"; then
    abort "Could not determine the current AWS account (aws sts get-caller-identity failed). Check your credentials."
  fi
  if [ "$current_account" != "$EXPECTED_ACCOUNT_ID" ]; then
    abort "Account mismatch.

Expected account: $EXPECTED_ACCOUNT_ID
Current account:  $current_account"
  fi
  echo "Account verified: $current_account"
}

verify_volume_state() {
  local state attachment_count
  if ! state="$(aws ec2 describe-volumes --region "$REGION" --volume-ids "$VOLUME_ID" --query 'Volumes[0].State' --output text 2>/dev/null)"; then
    abort "Volume $VOLUME_ID was not found in $REGION. It may already have been deleted."
  fi
  if [ "$state" != "available" ]; then
    abort "Resource state changed since CloudZombie analysis.

Expected volume state: available
Current volume state:  $state"
  fi
  attachment_count="$(aws ec2 describe-volumes --region "$REGION" --volume-ids "$VOLUME_ID" --query 'length(Volumes[0].Attachments)' --output text)"
  if [ "$attachment_count" != "0" ]; then
    abort "Resource state changed since CloudZombie analysis.

The volume now reports $attachment_count attachment(s)."
  fi
  echo "Volume state verified: available with 0 attachments"
}

verify_volume_tags() {
  local ignore_value stack_name
  ignore_value="$(aws ec2 describe-volumes --region "$REGION" --volume-ids "$VOLUME_ID" --query "Volumes[0].Tags[?Key=='${IGNORE_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$ignore_value" != "None" ] && [ "$(to_lower "$ignore_value")" = "$(to_lower "$IGNORE_TAG_VALUE")" ]; then
    abort "Resource is now marked to be ignored ($IGNORE_TAG_KEY=$ignore_value)."
  fi
  stack_name="$(aws ec2 describe-volumes --region "$REGION" --volume-ids "$VOLUME_ID" --query "Volumes[0].Tags[?Key=='${CLOUDFORMATION_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$stack_name" != "None" ] && [ -n "$stack_name" ]; then
    abort "Resource now carries the $CLOUDFORMATION_TAG_KEY tag (stack: $stack_name). Change the CloudFormation stack instead of deleting the volume manually."
  fi
  echo "Ignore-tag check passed; no CloudFormation stack tag present"
}

show_current_volume() {
  echo
  echo "Current volume as reported by AWS right now:"
  aws ec2 describe-volumes --region "$REGION" --volume-ids "$VOLUME_ID" --output table
  echo
  echo "Ownership note: CloudZombie found no CloudFormation evidence for this volume, but"
  echo "that does not prove it is unmanaged. Terraform or other tooling may still own it."
}

offer_snapshot() {
  local answer snapshot_id
  echo
  printf 'Create a snapshot of %s before deleting it? [y/N] ' "$VOLUME_ID"
  read -r answer
  case "$answer" in
    y|Y)
      if ! snapshot_id="$(aws ec2 create-snapshot --region "$REGION" --volume-id "$VOLUME_ID" --description "CloudZombie pre-deletion snapshot" --query SnapshotId --output text)"; then
        abort "Snapshot creation failed; the volume was not deleted."
      fi
      echo "Waiting for snapshot $snapshot_id to complete..."
      if ! aws ec2 wait snapshot-completed --region "$REGION" --snapshot-ids "$snapshot_id"; then
        abort "Snapshot $snapshot_id did not complete; the volume was not deleted."
      fi
      echo "Snapshot $snapshot_id completed. It incurs snapshot storage charges until you delete it."
      ;;
    *)
      echo "No snapshot will be created."
      ;;
  esac
}

confirm_deletion() {
  local confirmation
  echo
  echo "This will permanently delete EBS volume $VOLUME_ID in $REGION (account $EXPECTED_ACCOUNT_ID)."
  printf 'Type DELETE %s to continue: ' "$VOLUME_ID"
  read -r confirmation
  if [ "$confirmation" != "DELETE $VOLUME_ID" ]; then
    abort "Confirmation did not match."
  fi
}

main() {
  require_aws_cli
  verify_account
  verify_volume_state
  verify_volume_tags
  show_current_volume
  offer_snapshot
  confirm_deletion
  aws ec2 delete-volume --region "$REGION" --volume-id "$VOLUME_ID"
  echo
  echo "Deleted volume $VOLUME_ID in $REGION."
}

main "$@"
