#!/usr/bin/env bash
# Generated by CloudZombie - read-only investigation script
# Kind:             investigation
# Detector:         stopped_ec2_instance
# Generated at:     2026-09-20T10:00:00Z
# Scan ID:          11111111-1111-4111-8111-111111111111
# Expected account: 123456789012
# Region:           us-east-1
# Resource:         i-0a1b2c3d4e5f60001
#
# CloudZombie never executes this script. It analyses AWS through read-only API calls
# only and generates this file for a human to review and run separately. Every AWS CLI
# call below names the region explicitly, re-validates the live resource state, and
# aborts on any unexpected condition.
set -euo pipefail
readonly EXPECTED_ACCOUNT_ID="123456789012"
readonly REGION="us-east-1"
readonly INSTANCE_ID="i-0a1b2c3d4e5f60001"


abort() {
  echo
  echo "ABORTED"
  echo
  echo "$1"
  echo
  echo "No action performed."
  exit 1
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

require_aws_cli() {
  if ! command -v aws >/dev/null 2>&1; then
    abort "The AWS CLI (aws) is not installed or not on PATH."
  fi
}

verify_account() {
  local current_account
  if ! current_account="$(aws sts get-caller-identity --region "$REGION" --query Account --output text 2>/dev/null)"; then
    abort "Could not determine the current AWS account (aws sts get-caller-identity failed). Check your credentials."
  fi
  if [ "$current_account" != "$EXPECTED_ACCOUNT_ID" ]; then
    abort "Account mismatch.

Expected account: $EXPECTED_ACCOUNT_ID
Current account:  $current_account"
  fi
  echo "Account verified: $current_account"
}

investigation_banner() {
  echo
  echo "CloudZombie investigation script (read-only)."
  echo "This script only runs describe-* commands. It performs no changes."
  echo
}

main() {
  require_aws_cli
  verify_account
  investigation_banner
  echo "Instance $INSTANCE_ID in $REGION:"
  aws ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE_ID" --output table
  echo
  echo "EBS volumes attached to the instance (billed while it is stopped):"
  aws ec2 describe-volumes --region "$REGION" --filters "Name=attachment.instance-id,Values=$INSTANCE_ID" --output table
  echo
  echo "Elastic IP addresses associated with the instance (billed while it is stopped):"
  aws ec2 describe-addresses --region "$REGION" --filters "Name=instance-id,Values=$INSTANCE_ID" --output table
  echo
  echo "CloudZombie does not generate termination commands. Confirm with the instance owner"
  echo "whether it is still needed, and evaluate the attached volumes and addresses separately."
}

main "$@"
