#!/usr/bin/env bash
# Generated by CloudZombie - guarded remediation script
# Kind:             guarded_remediation
# Detector:         unassociated_elastic_ip
# Generated at:     2026-09-20T10:00:00Z
# Scan ID:          11111111-1111-4111-8111-111111111111
# Expected account: 123456789012
# Region:           us-east-1
# Resource:         eipalloc-0a1b2c3d4e5f60001
#
# CloudZombie never executes this script. It analyses AWS through read-only API calls
# only and generates this file for a human to review and run separately. Every AWS CLI
# call below names the region explicitly, re-validates the live resource state, and
# aborts on any unexpected condition.
set -euo pipefail
readonly EXPECTED_ACCOUNT_ID="123456789012"
readonly REGION="us-east-1"
readonly ALLOCATION_ID="eipalloc-0a1b2c3d4e5f60001"
readonly IGNORE_TAG_KEY="cloudzombie:ignore"
readonly IGNORE_TAG_VALUE="true"
readonly CLOUDFORMATION_TAG_KEY="aws:cloudformation:stack-name"


abort() {
  echo
  echo "ABORTED"
  echo
  echo "$1"
  echo
  echo "No action performed."
  exit 1
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

require_aws_cli() {
  if ! command -v aws >/dev/null 2>&1; then
    abort "The AWS CLI (aws) is not installed or not on PATH."
  fi
}

verify_account() {
  local current_account
  if ! current_account="$(aws sts get-caller-identity --region "$REGION" --query Account --output text 2>/dev/null)"; then
    abort "Could not determine the current AWS account (aws sts get-caller-identity failed). Check your credentials."
  fi
  if [ "$current_account" != "$EXPECTED_ACCOUNT_ID" ]; then
    abort "Account mismatch.

Expected account: $EXPECTED_ACCOUNT_ID
Current account:  $current_account"
  fi
  echo "Account verified: $current_account"
}

verify_address_state() {
  local association_id instance_id network_interface_id
  if ! association_id="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --query 'Addresses[0].AssociationId' --output text 2>/dev/null)"; then
    abort "Elastic IP allocation $ALLOCATION_ID was not found in $REGION. It may already have been released."
  fi
  instance_id="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --query 'Addresses[0].InstanceId' --output text)"
  network_interface_id="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --query 'Addresses[0].NetworkInterfaceId' --output text)"
  if [ "$association_id" != "None" ] || [ "$instance_id" != "None" ] || [ "$network_interface_id" != "None" ]; then
    abort "Resource state changed since CloudZombie analysis.

The address is now associated.
AssociationId:      $association_id
InstanceId:         $instance_id
NetworkInterfaceId: $network_interface_id"
  fi
  echo "Address state verified: not associated with any instance or network interface"
}

verify_address_tags() {
  local ignore_value stack_name
  ignore_value="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --query "Addresses[0].Tags[?Key=='${IGNORE_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$ignore_value" != "None" ] && [ "$(to_lower "$ignore_value")" = "$(to_lower "$IGNORE_TAG_VALUE")" ]; then
    abort "Resource is now marked to be ignored ($IGNORE_TAG_KEY=$ignore_value)."
  fi
  stack_name="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --query "Addresses[0].Tags[?Key=='${CLOUDFORMATION_TAG_KEY}'].Value | [0]" --output text)"
  if [ "$stack_name" != "None" ] && [ -n "$stack_name" ]; then
    abort "Resource now carries the $CLOUDFORMATION_TAG_KEY tag (stack: $stack_name). Change the CloudFormation stack instead of releasing the address manually."
  fi
  echo "Ignore-tag check passed; no CloudFormation stack tag present"
}

show_current_address() {
  echo
  echo "Current Elastic IP as reported by AWS right now:"
  aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOCATION_ID" --output table
  echo
  echo "WARNING: releasing an Elastic IP returns it to the AWS pool. You may not be able to"
  echo "recover the same public IPv4 address afterwards. Check DNS records and allow-lists first."
  echo
  echo "Ownership note: CloudZombie found no CloudFormation evidence for this address, but"
  echo "that does not prove it is unmanaged. Terraform or other tooling may still own it."
}

confirm_release() {
  local confirmation
  echo
  echo "This will release Elastic IP allocation $ALLOCATION_ID in $REGION (account $EXPECTED_ACCOUNT_ID)."
  printf 'Type RELEASE %s to continue: ' "$ALLOCATION_ID"
  read -r confirmation
  if [ "$confirmation" != "RELEASE $ALLOCATION_ID" ]; then
    abort "Confirmation did not match."
  fi
}

main() {
  require_aws_cli
  verify_account
  verify_address_state
  verify_address_tags
  show_current_address
  confirm_release
  aws ec2 release-address --region "$REGION" --allocation-id "$ALLOCATION_ID"
  echo
  echo "Released Elastic IP allocation $ALLOCATION_ID in $REGION."
}

main "$@"
