#!/usr/bin/env bash
# Generated by CloudZombie - read-only investigation script
# Kind:             investigation
# Detector:         snapshot_missing_source_volume
# Generated at:     2026-09-20T10:00:00Z
# Scan ID:          11111111-1111-4111-8111-111111111111
# Expected account: 123456789012
# Region:           eu-central-1
# Resource:         snap-0a1b2c3d4e5f60001
#
# CloudZombie never executes this script. It analyses AWS through read-only API calls
# only and generates this file for a human to review and run separately. Every AWS CLI
# call below names the region explicitly, re-validates the live resource state, and
# aborts on any unexpected condition.
set -euo pipefail
readonly EXPECTED_ACCOUNT_ID="123456789012"
readonly REGION="eu-central-1"
readonly SNAPSHOT_ID="snap-0a1b2c3d4e5f60001"


abort() {
  echo
  echo "ABORTED"
  echo
  echo "$1"
  echo
  echo "No action performed."
  exit 1
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

require_aws_cli() {
  if ! command -v aws >/dev/null 2>&1; then
    abort "The AWS CLI (aws) is not installed or not on PATH."
  fi
}

verify_account() {
  local current_account
  if ! current_account="$(aws sts get-caller-identity --region "$REGION" --query Account --output text 2>/dev/null)"; then
    abort "Could not determine the current AWS account (aws sts get-caller-identity failed). Check your credentials."
  fi
  if [ "$current_account" != "$EXPECTED_ACCOUNT_ID" ]; then
    abort "Account mismatch.

Expected account: $EXPECTED_ACCOUNT_ID
Current account:  $current_account"
  fi
  echo "Account verified: $current_account"
}

investigation_banner() {
  echo
  echo "CloudZombie investigation script (read-only)."
  echo "This script only runs describe-* commands. It performs no changes."
  echo
}

# REVIEW REQUIRED - deletion is intentionally disabled in this script.
# Only after confirming that no AMI, sharing, backup plan or lock depends on the
# snapshot, and understanding that incremental snapshots may free less than their
# apparent size, you may run the following command yourself:
# aws ec2 delete-snapshot --region "$REGION" --snapshot-id "$SNAPSHOT_ID"

main() {
  require_aws_cli
  verify_account
  investigation_banner
  echo "Snapshot $SNAPSHOT_ID in $REGION:"
  aws ec2 describe-snapshots --region "$REGION" --snapshot-ids "$SNAPSHOT_ID" --output table
  echo
  echo "Sharing (createVolumePermission):"
  aws ec2 describe-snapshot-attribute --region "$REGION" --snapshot-id "$SNAPSHOT_ID" --attribute createVolumePermission --output table
  echo
  echo "AMIs owned by this account that reference the snapshot:"
  aws ec2 describe-images --region "$REGION" --owners self --filters "Name=block-device-mapping.snapshot-id,Values=$SNAPSHOT_ID" --output table
  echo
  echo "Snapshot lock status:"
  aws ec2 describe-locked-snapshots --region "$REGION" --snapshot-ids "$SNAPSHOT_ID" --output table || echo "(lock status unavailable)"
  echo
  echo "Snapshots are incremental: deleting this snapshot may free less storage than its"
  echo "apparent size. Only blocks not referenced by other snapshots are reclaimed."
  echo
  echo "REVIEW REQUIRED - deletion is intentionally disabled in this script."
  echo "If, after review, you decide to delete the snapshot, run the command below manually:"
  echo "#   aws ec2 delete-snapshot --region \"$REGION\" --snapshot-id \"$SNAPSHOT_ID\""
}

main "$@"
